stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
      - data/accidents_full.csv
      - src/data/make_dataset.py
    outs:
      - data/preprocessed
  train-track:
    cmd: python src/track_experiment.py
    deps:
      - data/preprocessed
      - src/track_experiment.py
    outs:
      - models/xgb_model.pkl
    metrics:
      - metrics/metrics.json
