name: New_Accident Prediction Pipeline

# Trigger the workflow on push to main or pull requests

on:
  pull_request:
  push:
    branches: [ "master" , "feature/airflow_grafana_ci"]
  
permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest -q

  docker-build:
    name: Docker build Validattion
    runs-on: ubuntu-latest
  
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Show workspace
      - name: Show workspace
        run: |
          pwd
          ls -R

      # Set up Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Docker Compose Version
      - name: Docker Compose version
        run: |
          sudo apt-get update
          docker compose version
      
      # Build base image
      - name: Build base image
        run: docker build -t ml-base:latest ./docker/ml-base
      
      # Build all services
      - name: Build Docker Compose stack
        run: |
          docker compose build

      # Start services in background
      - name: Start services
        run: |
          docker compose up -d

      # Wait for services to stabilize
      - name: Wait for services
        run: |
          echo "Waiting for services..."
          sleep 30

      # Check running containers
      - name: Docker ps
        run: docker ps

      # Tear down stack
      - name: Shutdown services
        if: always()
        run: |
          docker compose down -v